# -*- coding: utf-8 -*-
"""apuntes_10_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0nMpGxJpWacDTVD-sOYyvlSc6_cxHSr
"""

import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import altair as alt

# Configuración del estilo visual
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)
# Deshabiltar el límite de 5000 filas de Altair
alt.data_transformers.enable('default', max_rows=None)
print('Librerias importadas')

# Carga y limpieza de datos
url = "https://data.insideairbnb.com/mexico/df/mexico-city/2026-06-15/data/listings.csv.gz"
print('Dataset cargado')
try:
  df = pl.read_csv(url)
  print('Dataset cargado exitosamente')
except Exception as e:
  print(f'Error al cargar el dataset: {e}')

# Limpieza inicial
if not df.is_empty():
  df = df.with_columns(
      pl.col('price')
      .str.replace_all(r'\$', '')
      .str.replace_all(r",","")
      .cast(pl.Float64, strict=False)
      .alias("price")
  ).drop_nulls(
      subset=['price']
  ).filter(
      pl.col('price') > 0
  )

  print("Limpiza inicial realizada")
  display(df.head())

# Análisis básico
print ("1. ¿Cuál es precio promedio por noche?")
avg_price = df.select (pl.col('price').mean()).item()
print(f'El precio promedio por noche es de: {avg_price}')
print('2. ¿Cuáles son los tipos de alojamiento?')
room_types = (
    df.group_by('room_type')
    .agg(pl.len()
    .alias('count'))
    .sort('count', descending=True)
)
print(room_types)
print('3. ¿Cuáles son las 10 alcaldías con más alojamientos?')
top_10 = (
    df.group_by('neighbourhood_cleansed')
    .agg(pl.len().alias('count'))
    .sort('count',descending=True)
    .head(10)
)
print(top_10)
print (' 4. ¿Quiénes son los anfitriones con más alojamientos?')
top_hosts = (
     df.group_by('host_name')
     .agg(pl.len()
     .alias('count'))
     .sort('count', descending=True)
     .head(10)
)
print(top_hosts)

# Visualizaciones

price_to_plot_df = df.filter(pl.col('price')<df.select(pl.col('price').quantile(0.95)).item()).to_pandas()

# Usando altair
chart_list = alt.Chart(price_to_plot_df).mark_bar().encode(alt.X('price:Q', bin = alt.Bin(maxbins=50),title='Precio por noche'),alt.Y('count()', title='Frecuencia')
,tooltip=[alt.Tooltip('count()',title='Frecuencia'), alt.Tooltip('price:Q', bin=True, title='Rango de precio')]
                                                           ).properties(title='Distribución de precios por noche',width=700,
                                                           height=400)
chart_list.show()

# Graficar el top de las alcaldias
top_alcaldias_pd = top_10.to_pandas()

fig_hoods = px.bar(
    top_alcaldias_pd,
    y='neighbourhood_cleansed',
    x='count',
    title='Top 10 de las alcaldías con más alojamientos',
    orientation='h',
    labels={'count': 'Número de alojamientos', 'neighbourhood_cleansed': 'Alcaldía'},
    color = 'count',
    color_continuous_scale = px.colors.sequential.Viridis
)
fig_hoods.show()

# Grafico de mapa geográfico
df_sample_for_plot = df.filter(pl.col('price')<df.select(pl.col('price').quantile(0.95)).item()).sample(n=5000, seed=42).to_pandas()

fig_map = px.scatter_mapbox(
    df_sample_for_plot,
    lat='latitude',
    lon='longitude',
    color='price',
    size='price',
    color_continuous_scale=px.colors.sequential.Viridis,
    size_max=15,
    zoom=10,
    mapbox_style = 'carto-positron',
    hover_name = 'name',
    hover_data = {'neighbourhood_cleansed': True, 'price': '$.2f'}
)
fig_map.update_layout(
    title = 'Mapa interactivo de Precios de Airbnb en CDMX',
    legend_title_text = 'Precio (MXN)'
)
fig_map.show()